include:
  - fqbn: esp32:esp32:featheresp32

additional_urls:
  - core: esp32:esp32
    url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

exclude:
  # Disabled SPI these SPI examples for specific boards until setDataMode is replaced in the library
  - sketch:
      - examples/spi_command/spi_command.ino
      - examples/spi_background/spi_background.ino
    fqbn:
      - arduino:renesas_uno:minima
      - arduino:renesas_uno:unor4wifi
      - arduino:samd:mkrzero