name: build-check

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '30 3 1-7 * 5' # Run on the first Friday of every month at 3:30 AM UTC
      
jobs:
  build-arduino-uno:
    name: Build Arduino Uno before running full matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno

  build:
    needs: build-arduino-uno
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: arduino:avr:nano
          - fqbn: arduino:esp32:nano_nora
          - fqbn: arduino:megaavr:uno2018:mode=off
          - fqbn: arduino:renesas_uno:minima
            skip_spi: true # Disabled until setDataMode is replaced in the library
          - fqbn: arduino:renesas_uno:unor4wifi
            skip_spi: true # Disabled until setDataMode is replaced in the library
          - fqbn: arduino:samd:mkrzero
            skip_spi: true # Disabled until setDataMode is replaced in the library
          - fqbn: "Infineon:xmc:XMC1100_XMC2GO"
            platform-name: Infineon:xmc
          - fqbn: "Infineon:xmc:XMC1300_Boot_Kit"
            platform-name: Infineon:xmc
          - fqbn: "Infineon:xmc:XMC1400_XMC2GO"
            platform-name: Infineon:xmc
          - fqbn: "Infineon:xmc:XMC1400_Arduino_Kit"
            platform-name: Infineon:xmc
          - fqbn: "Infineon:xmc:XMC4700_Relax_Kit"
            platform-name: Infineon:xmc
          - fqbn: "Infineon:xmc:XMC1100_Boot_Kit"
            platform-name: Infineon:xmc
          - fqbn: "infineon:psoc6:cy8ckit_062s2_ai"
            platform-name: infineon:psoc6
            skip_spi: true # Disabled until SPI is enabled for PSOC6 Arduino core
          - fqbn: "esp32:esp32:esp32"
            platform-name: esp32:esp32

        include:
          - board:
              platform-name: Infineon:xmc
            platforms: |
              - name: Infineon:xmc
                source-url: https://github.com/Infineon/XMC-for-Arduino/releases/latest/download/package_infineon_index.json  
          
          - board:
              platform-name: infineon:psoc6
            platforms: |
              - name: infineon:psoc6
                source-url: https://github.com/Infineon/arduino-core-psoc6/releases/latest/download/package_psoc6_index.json

          - board:
              platform-name: esp32:esp32
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
    
    name: Build for ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Compile I2C examples
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          sketch-paths: |
            - examples/i2c_background
            - examples/i2c_command
            - examples/i2c_interrupt
      
      - name: Compile SPI examples
        if: ${{ !matrix.board.skip_spi }}
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          sketch-paths: |
            - examples/spi_command
            - examples/spi_background